# room_gui.py

# ########
# Packages
# ########
import tkinter as tk
from tkinter import messagebox
import tkinter.ttk as ttk # for combobox
from tkinter.messagebox import showinfo
from tkinter.messagebox import askyesno

from room_dao import RoomDAO # To communicate with room table
from validation import Validation


# #################
# RoomGUI Class
# #################

class RoomGUI():
    """RoomGUI class to implement CRUD functionalities & methods to manage the user interface"""

    def __init__(self):   
        """Initialiser"""
    
        # Instantiate a data access object 
        # Contains methods to access the database
        self.room_dao = RoomDAO()

        # Instantiate a validation object
        # Contains methods to validate input fields
        self.validator = Validation()

        # Form fields
        # Instantiate stringvars - hold  data entered in  fields of form
        self.room_id = tk.StringVar()
        self.room_price = tk.DoubleVar()
        self.room_num = tk.StringVar()
        self.room_type_id = tk.StringVar()

        # List of room ids - lb for listbox
        self.lb_ids = None

        # search
        self.search_room = None
        # search list
        self.ln_ids = None

        # Messagebox title
        self.mb_title_bar = "room CRUD"

    def create_gui(self, root):
        """
        Create a high level frame which contains the entire GUI 
        (of this part of the application) and adds it to the root window.
        Notice that the "root" window is passed the second parameter in the 
        method header.
        Also notice that the first (and mandatory) parameter to all methods 
        is "self" i.e. a reference to the object instantiated from the class.
        """

        print("\nCreating room GUI ...")

        room_frame = tk.Frame(root)
        room_frame.pack()

        form_frame = tk.Frame(room_frame)
        form_frame.pack()
    
        tk.Label(
            form_frame, 
            font=('arial', 10), 
            text = "Room").grid(row=0, column=0, columnspan=3)

        # row 1: room_id label, room_id entry and list_of_ids label
        tk.Label(
            form_frame, 
            text= "Room Id", 
            font=('arial', 10), 
            width=20, 
            anchor="e", 
            bd=1, 
            pady=10, 
            padx=10).grid(row=1, column=0)
        # Need to use both padx and pady to leave a vertical space between rows of labels
        # And a space between the  label and its entry field
        # Entry has no padding options
        # Use the width= option to specify how wide in terms of number of characters
        tk.Entry(
            form_frame, 
            textvariable=self.room_id, 
            width=30, 
            bd=1, 
            state=tk.DISABLED).grid(row=1, column=1)
        # room_id is disabled to prevent user from entering a value
        # room_id is generated by the database because AUTOINCREMENT 
        # was specified in the database schema
        tk.Label(
            form_frame, 
            text= "Room IDs", 
            font=('arial', 10)).grid(row=1, column=2)
        
        # ***search by lastname
        tk.Label(
            form_frame, 
            text= "Search by room type", 
            font=('arial', 10)).grid(row=7, column=2)
        self.search_room = tk.Entry(form_frame)
        self.search_room.grid(row=8, column=2)

        # row 2: room_num label and entry (the listbox will go through)
        tk.Label(
            form_frame, 
            text= "Room no", 
            font=('arial', 10), 
            width=20, 
            anchor="e", 
            bd=1, 
            pady=10, 
            padx=10).grid(row=2, column=0)
        tk.Entry(
            form_frame, 
            textvariable=self.room_num, 
            width=30, 
            bd=1).grid(row=2, column=1)

        # row 3: room_price label, room_price entry and listbox of ids
        tk.Label(
            form_frame, 
            text= "Room price", 
            font=('arial', 10), 
            width=20, 
            anchor="e", 
            bd=1, 
            pady=10, 
            padx=10).grid(row=3, column=0)
        tk.Entry(
            form_frame, 
            textvariable=self.room_price, 
            width=30, 
            bd=1).grid(row=3, column=1)
        # Use the height= option to specify the height, default is 10
        # Use the width= option to specify the number of characters, default is 20
        self.lb_ids = tk.Listbox(form_frame)
        self.lb_ids.grid(row=2, column=2, rowspan=5) 
        # 'self' means instance attribute rather than local variable
        # since python allows using variables before they are declared
        # it does not matter whether lb_ids has been declared or not at the 
        # top of the file before the methods definition
        # Set the method to be called when an item is clicked on the listbox 
        self.lb_ids.bind('<<ListboxSelect>>', self.on_list_select)


        # row 4: room_type_id and entry (the listbox will go through)
        tk.Label(
            form_frame, 
            text= "Room type", 
            font=('arial', 10), 
            width=20, 
            anchor="e", 
            bd=1, 
            pady=10, 
            padx=10).grid(row=4, column=0)

        # create a combobox
        selected_item = tk.StringVar()
        item_cb = ttk.Combobox(form_frame, width=28,textvariable=self.room_type_id)
        item_cb['state'] = 'readonly'

        retrieved_df = self.room_dao.retrieve_data('room_type')

        item_cb['values'] = [tpl[0] for tpl in retrieved_df]

        # place the widget
        item_cb.grid(row=4, column=1)

        # bind the selected value changes
        def item_changed(event):
            """ handle the month changed event """
            selected_item = self.room_type_id
            showinfo(
                title='Result',
                message=f'You selected {selected_item.get()}!'
            )

        item_cb.bind('<<ComboboxSelected>>', item_changed)

        # Buttons
        # There are 3 columns of widgets in the frame and 4 buttons
        # Better insert the button in another frame
        # Also easier to pack them from the left than using a grid with row 
        # and col locations
        # pady to leave a space from frame on top
        button_frame = tk.LabelFrame(room_frame, pady=10, text="Commands") 
        button_frame.pack()
        # Use the anchor= option to position the button
        # External padding around buttons: padx= pady=  default is 0
        # Use the width= option to specify the number of characters, 
        # otherwise calculated based on text width
        tk.Button(
            button_frame, 
            width=10, text="Clear", 
            command=self.clear_fields).pack(side=tk.LEFT)
        tk.Button(
            button_frame, 
            width=10, 
            text="Save", 
            command=self.save).pack(side=tk.LEFT)
        tk.Button(
            button_frame, 
            width=10, 
            text="Delete", 
            command=self.confirm_delete).pack(side=tk.LEFT)
        tk.Button(
            button_frame, 
            width=10, 
            text="Load", 
            command=self.load).pack(side=tk.LEFT)       
        tk.Button(
            button_frame, 
            width=10, 
            text="Search", 
            command=self.filter_by_room_type).pack(side=tk.LEFT) 
        # Return a reference to the high level frame created
        # Will need the reference to be able to destroy it in the calling function
        return room_frame

    def confirm_delete(self):
        """
        Show confirmation popup before executing delete. 

        Parameters: None

        Return: None
        """
        answer = askyesno(title='confirmation',
                        message=f'Are you sure that you want to delete?')
        if answer:
            self.delete()
    
    def clear_fields(self):
        """Clear the fields of the form"""

        print("\nClearing fields ...")

        # Just blank all the fields
        self.room_id.set("")
        self.room_price.set("")
        self.room_num.set("")
        self.room_type_id.set("")

    def save(self):
        """Save the data displayed on the form to the database."""


        print("\nSaving a room ...")

        # Get the data
        data = self.get_fields()   

        # Validate the data
        valid_data, message = self.validate_fields(data)
        if valid_data:
            if (len(data['room_id'])==0):
                # If nothing has been entered in room_id 
                # i.e. its length is zero characters
                print("Calling create() as room_id is absent")
                self.create(data)
            else:
                print("Calling update() as room_id is present")
                self.update(data)
                pass
        else:
            message_text = "Invalid fields.\n" + message 
            messagebox.showwarning(self.mb_title_bar, message_text, icon="warning")
            pass

        # automatic load lists after save  
        self.load()

    def get_fields(self):
        """Get the data entered in the fields of the form"""

        print("\nGetting fields ...")

        room = {}
        # room_id is ignored when creating a record
        room['room_id'] = self.room_id.get() 
        room['room_price'] = self.room_price.get()
        room['room_num'] = self.room_num.get()
        room['room_type_id'] = self.room_type_id.get()

        print(f"room: {room}")
 
        return room    

    def create(self, data):
        """Create a new record in the database"""

        print("\nCreating a room ...")
        print(f"data: {data}")

        result = self.room_dao.create(data)

        # Display the returned message to the user - use a messagebox
        # Format: message.function(title, message [, options])
        # Functions: showinfo, showwarning, showerror, askquestion, 
        #            askokcancel, askyesno, or askretrycancel
        # Use the icon= option to specify which icon to display 
        # e.g. icon="warning", "error", "info", "question"     
        # Display everything that is returned in the result
        messagebox.showinfo(self.mb_title_bar, result)
        self.load()

    def update(self, data):
        """Update a record in the database"""

        print("\nUpdating a room ...")
        print(f"data: {data}")

        result = self.room_dao.update(data['room_id'], data)

        # Display the returned message to the user - use a messagebox  
        # Display everything that is returned in the result      
        messagebox.showinfo(self.mb_title_bar, result)
        self.load()

    def delete(self):
        """Delete a record from the database"""

        print("\nDeleting  a room ...")
        
        # Grab the room_id from the stringvar
        id = self.room_id.get() 
        print(f"id: {id}")
        
        # Call the data access object to do the job
        # Pass the id as parameter to the delete() method
        result = self.room_dao.delete(id)   

        # Display the returned message to the user - use a messagebox    
        # Display everything that is returned in the result    
        messagebox.showinfo(self.mb_title_bar, result)
        self.load()

    def load(self):
        """Retrieve a list of IDs from the database and load them into a listbox"""

        print("\nLoading IDs in list box ...")

        result = self.room_dao.find_ids()
        print(f"result: {result}")

        # Check if there is an entry in the result dictionary
        if "room_ids" in result: 
            list_ids = result['room_ids'] # will crash if there is no entry!
            # Set the returned list into the listbox
            # Before doing that, must clear any previous list in the box
            self.lb_ids.delete(0,tk.END)
            print("Setting room_ids in listbox ...")
            for x in list_ids:
                self.lb_ids.insert(tk.END, x)
                #print(x)
            pass

    def filter_by_room_type(self):
        """Retrieve a list of filtered IDs from the database and load them into a listbox"""

        print("\nLoading filtered IDs in list box ...")

        room_type_id = self.search_room.get()
        result = self.room_dao.find_by_room_tlt(room_type_id)

        if "filtered_room_tlts_ids" in result: 
            list_ids = result['filtered_room_tlts_ids'] # will crash if there is no entry!
            # Set the returned list into the listbox
            # Before doing that, must clear any previous list in the box
            self.lb_ids.delete(0,tk.END)
            print("Setting filtered_room_tlts_ids in listbox ...")
            for x in list_ids:
                self.lb_ids.insert(tk.END, x)
                #print(x)
            pass
         
    def on_list_select(self, evt):
        """on_list_select() is triggered when a user clicks an item in the listbox"""

        print("\nSelecting an item from the list box ...")

        w = evt.widget

        # index = position of the item clicked in the list, first item is item 0 not 1
        index = int(w.curselection()[0]) 
          
         # value of the item clicked, in our case it's the room_id  
        value = w.get(index) 
         
        print(f"index: {index}") 
        print(f"value: {value}")

        # Call find_by_id and populate the stringvars of the form
        result = self.room_dao.find_by_id(value)

        # { "room" : {"room_dao": "", "first_name": "", etc}}
        print(f"result: {result}") 

        # Grab room dict from result dict and use it to populate the fields on the form  
        room = result['room']
        self.populate_fields(room)

    def populate_fields(self, room):
        """Populate the fields of the form with data"""

        print("\nPopulating fields ...")
        print(f"room: {room}")

        # Set the values from the dict to the stringvars
        self.room_id.set(room['room_id'])
        self.room_price.set(room['room_price'])
        self.room_num.set(room['room_num'])
        self.room_type_id.set(room['room_type_id'])

    def validate_fields(self, data):
        """Validate the data entered in the fields of the form"""

        print("\nValidating the data ...")
        print(f"data: {data}")
           
        # By default set to true, anything wrong will turn it to false   
        valid_data = True 
        # Instantiate an empty list to contain the messages
        message_list = [] 
        
        # Check for blank fields
        # Do not check room_id as this is generated by the database
        if not str(data['room_price']):
            valid_data = False
            message_list.append("room price is empty")
        if not str(data['room_num']):
            valid_data = False
            message_list.append("room number is empty")
        if not str(data['room_type_id']):
            valid_data = False
            message_list.append("room type id is empty")

        # Check if room_price contain  
        # only numeric characters (and may be certain special characters)
        if not self.validator.is_numeric(data['room_price']):
            valid_data = False
            message_list.append("invalid room price")

        # Check if room number contain  
        # only numeric characters (and may be certain special characters)
        if not self.validator.is_numeric(data['room_num']):
            valid_data = False
            message_list.append("invalid room number")

        # Check if room type id contain  
        # only numeric characters (and may be certain special characters)
        if not self.validator.is_numeric(data['room_type_id']):
            valid_data = False
            message_list.append("invalid room type id")

        # Join the items in the list as a string separated with a comma and a space    
        message = ', '.join(message_list) 

        return valid_data, message # return 2 values


# ###########
# Main method
# ###########

if __name__ == '__main__':
    """The main method is only executed when the file is 'run' (not imported in another file)"""
     
    # Setup a root window (in the middle of the screen)
    root = tk.Tk()
    root.title("Room System")
    screen_width = root.winfo_screenwidth()
    screen_height = root.winfo_screenheight()
    width = 900
    height = 500
    x = (screen_width/2) - (width/2)
    y = (screen_height/2) - (height/2)
    root.geometry('%dx%d+%d+%d' % (width, height, x, y))
    root.resizable(0, 0)

    # Instantiate the gui
    gui = RoomGUI()

    # Create the gui
    # pass the root window as parameter
    gui.create_gui(root)
    gui.load()
    # Run the mainloop 
    # the endless window loop to process user inputs
    root.mainloop()
    pass