import sqlite3

# 1. Open a connection
with sqlite3.connect("example.db") as conn:
    # 2. Get a cursor from the connection
    cur = conn.cursor()
    # 3. Use the cursor to execute the SQL
    cur.execute("""INSERT INTO person (firstname, lastname)
    VALUES ("Juyeon", "Kim");""") # person_id not mentioned, generated by the database
    # Note: when the with statement ends, cur and conn are closed automatically


